### ISSUE TITLE
is backup working already ?

### ISSUE THREAD

**Issue by DBarthe** [instaclustr/cassandra-operator#152]
Hello,

I've been playing with your operator and faced some issues regarding backups :
* When restoring a cluster, the sidecar-restore init container should configure the `initial_token` based on what is found on the manifest in the bucket storage. My solution was to create a configuration directory in the persistent volume where the sidecar-restore container can write additional config at runtime.
* When restarting a pod from a restored cluster, the sidecar-restore init container is still in the spec, therefore the restore happens twice. My solution was to create a lock on the persistent volume to prevent this to happen.

Does it make sense to you ? I can submit a PR to help fix the issue if you want to.

**Comment by benbromhead** [comment]
Thanks for reporting the issue. 

Currently the backup agent stores the token list on backup, however there is a todo for the restore task to generate a yaml fragment with initial_token set. With the fragment yaml configuration loader we have, this should be sufficient. 

I can look at fixing this, or if you want to have a go at it, I'm more than happy to help/guide/review when you are ready. 

If you are interested, the spot is here:

https://github.com/instaclustr/cassandra-operator/blob/ddad2e4a452f09f5c6bf31e36ded906b830c3e89/java/backup/src/main/java/com/instaclustr/backup/task/RestoreTask.java#L304-L317

As for the restore happening twice, this is because the target backup is still specified in the CassandraDataCenter resource. From an API perspective it's like you are always telling the operator to keep restoring from the backup. If you remove `restoreFromBackup` from `spec`, the operator will modify the underlying statefulset to no longer include the restore init definition.

From an ergonomics perspective I know this is not ideal, as its a little verbose and really after a successful restore, we shouldn't keep doing it. However, to properly address this issue we need to have better management around the state of in-progress restore and backup tasks. 

If we can track the progress of a restore properly, then we can have the operator handle this for us.

For the moment I will update the documentation to tell users that you need to modify the CDC resource after a successful restore.

**Comment by DBarthe** [comment]
Thanks @benbromhead for your quick answer,

I implemented a solution using the data volume to store extra configuration fragments generated at runtime by sidecars. Do you like this approach ?

**Comment by benbromhead** [comment]
The sidecar can certainly generate configuration fragments on its own, ideally though config is generated based on runtime/pod config and doesn't rely on storing config state in the data volume. 

The only persistent state we want to have to deal with is cassandra data in the data volume. Persistent config data should be stored in configmaps/crds etc, or be derivable by the operator from them.

So to answer your question, could your solution be generalizable to store that config outside of the data volume?

**Comment by DBarthe** [comment]
Not sure we can write to the config map from the sidecar, and get the result synced to the elassandra container before it starts.
Maybe the operator should find a way to set the initial token itself.

**Comment by benbromhead** [comment]
The pod will have a unique identity guarantee due to the properties of the stateful set. The ordinal and IP are guaranteed to be unique and follow the pod for the stateful sets lifetime. The backup agent should store the backup (and the token list) with the backup (e.g. in S3). 

On restore the agent can pull the token list associated with the backup from the backup location (apologies this is an exception to where config state can be stored). So if the sidecar pulls a backup it can set the initial_tokens based on the token list retrieved from the backup location. E.g. grab initial_token and dump to the config directory.

It only needs to do this once on restore. After the restore has been successful we don't need to keep setting initial_token as this information is stored in the system keyspace by Cassandra.

**Comment by DBarthe** [comment]
Thanks, that's simpler than what I thought initially. I'll try it that way and submit a PR soon.

**Comment by benbromhead** [comment]
Awesome
cc: @zegelin

**Comment by benbromhead** [comment]
Closing thanks to #160
