### ISSUE TITLE
Port backup/restore

### ISSUE THREAD

**Issue by benbromhead** [instaclustr/cassandra-operator#179]
Currently the Java operator supports taking backups and uploading them to S3, Azure, GCP and a filesystem based location. It also supports creating a new cluster and restoring an existing backup into it. 

The operator-sdk based version of our operator needs to support this.

**Comment by smiklosovic** [comment]
@zegelin please do the very first review of the backup-restore branch here. Due to size of that work, I can create PR or we can do this offline.

It is _not_ fully finished, for sure restores are not, but the main work is done and I would like to merge this sooner than later to build the complete restore functionally on it.

(1) https://github.com/smiklosovic/cassandra-operator/tree/backups-restores

**Comment by smiklosovic** [comment]
restores were finished here 

https://github.com/instaclustr/cassandra-operator/pull/254
