### ISSUE TITLE
Should we validate user's specs?

### ISSUE THREAD

**Issue by smiklosovic** [instaclustr/cassandra-operator#244]
It came to my mind when applying backup crds. We might want to validate specs and if fields which are necessary for backups to succeed are indeed set before proceeding. I was thinking about using this (1)

@johananl how is this solved in practice?

@zegelin @alourie any strong opinions here?

(1) https://github.com/asaskevich/govalidator

**Comment by alourie** [comment]
Well, if the **required** fields are not set, `kube apply` will error out when trying to load it into k8. So that's not an issue.

The question is whether we should validate the fields that were supplied for their correctness. I have no strong opinion here, maybe we could send them to sidecar as is in the request? The provided values are going to be marshalled into strings (or whatever types we define in the CRD), what else can we validate there?

**Comment by smiklosovic** [comment]
Yes you are right, we just omit "omitempty" and it will force that field to be there so it has to be set as such.

On the other hand, when e.g. for backups, `storageLocation` follows a predefined pattern, like "s3://myBucket", it is questionable if we leave this on sidecar to error out or we do these checks in operator ...

I think it will be better to leave it on sidecar though and it will error out transparently and statuses will be "FAILED".

**Comment by alourie** [comment]
Yes, I agree. I don't think that operator should check these.

**Comment by johananl** [comment]
This is an interesting question. Here is some info which can be useful. Apologize in advance if I'm telling you guys things you already know.

The very first line of defense is the k8s API itself: it validates CR fields according to the OpenAPI validation spec and ensures that all required fields are set and that field data types are OK.

However, when we want to validate more complex things, the OpenAPI validation doesn't help us. For that, there is a built-in k8s mechanism called [admission webhooks](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#what-are-admission-webhooks).

Webhooks allow us to run logic in response to calls to the API server and act on them. We can either *mutate* an API call or *validate* it. The k8s API server triggers an HTTP POST to a user-defined endpoint when a hook is triggered, which means there has to be some **server** which listens for incoming webhooks and handle them. **This server can be the operator**, but it can also be a separate component if desired.

Some k8s build-in functionality is implemented using admission webhooks, for example PSPs.

So, if we decide we need stronger validation, we should rely on this design pattern rather than implement our own admission controller inside the operator. This is something which can always be added later without breaking changes at the CRD level.

For more info and some examples: https://kubernetes.io/blog/2019/03/21/a-guide-to-kubernetes-admission-controllers/

**Comment by smiklosovic** [comment]
@johananl thanks for the information! Interesting indeed. I would leave it as it is for now but definitely food for thought.

**Comment by johananl** [comment]
Makes sense. Should I open an issue for tracking this?

**Comment by smiklosovic** [comment]
No. Just let it be really.
