### ISSUE TITLE
Recreate Missing Primitive Resources with Watchers

### ISSUE THREAD

**Issue by liwang-pivotal** [instaclustr/cassandra-operator#27]
Implement a thread to scan cluster status periodically. In addition to Issue #6  for provisioning, this thread should be alive through operator's life cycle. Also it should be able to detect resource failure/missing and rescue them back, hold the cluster in a desired state.

**Comment by liwang-pivotal** [comment]
PR #25 added a `CassandraPeriodicReconciliationService` to recreate missing primitive k8s resources periodically. However the down side of this design is the overhead for unnecessary reconcile and possible idle window to when repair is needed. The other way to go is to create watches for each primitive resource and capture deletion operation. Need to reevaluate this.

**Comment by benbromhead** [comment]
Thinking more about this, I wonder if it's better to rely on rbac to protect resources rather than try to recreate them?

**Comment by liwang-pivotal** [comment]
@benbromhead For some reason I didn't see this update in time... We had a discussion with Adam during the meeting today, and we agree on having both RBAC and `CassandraPeriodicReconciliationService` enabled as two layer protection because an authorized admin can also delete resource by mistake. It might be more robust for an operator to work as any other primitive resources like statefulset (eg. pod can be recreated immediately).

**Comment by zegelin** [comment]
My thinking was similar to how statefulsets work. You create a statefulset and the built-in controller creates pods, etc. If you delete one of those pods, the controller reacts immediatly by recreating it.

To the operator, statefulsets are like the pods, they should always exist if the data center exists.

We can add RBAC at a later stage (since its yet another thing to wrap our heads around). It would add an additional layer of protection, but more to prevent accedential deletion of Cassandra cluster resources.

@liwang-pivotal as discussed, rather than `CassandraPeriodicReconciliationService`, we can just react to events from the watches.

**Comment by liwang-pivotal** [comment]
@benbromhead Agree, I think watchers are more active too. Adam mentioned he already created those watchers, I will throw this `CassandraPeriodicReconciliationService` away once he pushes his : )

**Comment by benbromhead** [comment]
On further thinking about this, trying to recreate specific resources (especially statefulsets) if they are deleted manually is quite tricky.

We do react to ss changes, but I don't think it's the responsibility of the operator to try and fix up the many ways a user could mess with things. I think its just a matter of saying "if you mess with these resources, you are on your own and behavior is undefined"
